NOTIFICATION_TABLE_NAME = "NotificationPickup"
HEB_BASE_URL = "https://www.heb.com/commerce-api/v1/"
HEB_HOME_PAGE = "https://www.heb.com/"
MAPS_URL_LAT_LONG = "https://www.google.com/maps/search/?api=1&query={lat},{long}"
USPS_VALIDATION_URL = "https://m.usps.com/m/QuickZipAction?mode=2&tZip={ZIP}&jsonInd=Y"