# Python Function App to Linux on Azure

# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- az-func-release
  
variables:
    # Azure Resource Manager connection created during pipeline creation
    azureSubscription: '5200f476-ce80-430a-9e28-6d314fe42eaf'
  
    # Function app name
    functionAppName: 'Next-Pickup-Services'
  
    # Agent VM image name
    vmImageName: 'ubuntu-latest'
  
    # Working Directory
    workingDirectory: 'microservices'
  
stages:
  - stage: Build
    displayName: Build and Deploy Python Az Function
  
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: $(vmImageName)
  
      steps:

      - task: UsePythonVersion@0
        displayName: 'Set Python version to 3.7'
        inputs:
         versionSpec: '3.7'
         addToPath: true
         architecture: 'x64'

      - task: FuncToolsInstaller@0
        displayName: 'Install function Azure Functions Toolset for Deployment'
        inputs:
          version: 'latest'

      - task: AzureCLI@2
        displayName: 'Run build and publish command'
        inputs:
          azureSubscription: '$(azureSubscription)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            chmod a+x /usr/lib/azure-functions-core-tools/gozip
            cd $(workingDirectory)
            pwd
            func azure functionapp publish $(functionAppName) --python --build remote