trigger:
- az-func-release
  
variables:
    # Azure Resource Manager connection created during pipeline creation
    azureSubscription: '5200f476-ce80-430a-9e28-6d314fe42eaf'
  
    # Function app name
    functionAppName: 'Next-Pickup-Services'
  
    # Agent VM image name
    vmImageName: 'ubuntu-latest'
  
    # Working Directory
    workingDirectory: 'microservices'

    resourceGroupName: 'Next-Pickup'

jobs:
- job: Setup
  displayName: Setup Build Agent 
  pool:
    vmImage: $(vmImageName)
  
  steps:
  - task: UsePythonVersion@0
    displayName: 'Set Python version to 3.7'
    inputs:
      versionSpec: '3.7'
      addToPath: true
      architecture: 'x64'

  - task: FuncToolsInstaller@0
    displayName: 'Install function Azure Functions Toolset for Deployment'
    inputs:
      version: '3.0.2009'
  

- job: Deploy  
  displayName: Build and Publish All Functions
  dependsOn: Setup
  
  steps:
  - task: AzureCLI@2
    displayName: 'Run build and publish command'
    inputs:
      azureSubscription: '$(azureSubscription)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd $(workingDirectory)
        func azure functionapp publish $(functionAppName) --python --build remote
            
  - task: AzureAppServiceSettings@1
    displayName: 'Add the appropriate settings to the functions'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(functionAppName)
      resourceGroupName: $(resourceGroupName)
      appSettings: |
      [
        {
          "name": "MONGO_CONNECTION_STRING",
          "value": "$(dbConnectionString-dev)",
          "slotSetting": false
        }
      ]