trigger:
- client-release

jobs:
- job: Deploy
  displayName: Deploy Frontend 
  pool:
    vmImage: $(vmImageName)
  
  steps:
    - task: AzureFileCopy@4
      inputs:
        SourcePath: 'frontend'
        azureSubscription: $(azureSubscription)
        Destination: 'AzureBlob'
        storage: 'nextservicestorage'
        ContainerName: '$web'