trigger:
- client-release

jobs:
- job: Deploy
  displayName: Deploy Frontend 
  pool:
    vmImage: $(vmImageName)
  
  steps:
    - task: AzureFileCopy@4
      inputs:
        SourcePath: 'frontend'
        azureSubscription: 'Alex Projects(fab41ebf-515a-4a19-9475-daa31a196c92)'
        Destination: 'AzureBlob'
        storage: 'nextservicestorage'
        ContainerName: '$web'